# Generated by Django 3.2.7 on 2021-09-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='user',
            new_name='author',
        ),
    ]
